name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # ⬇️ PASSO 1: Configurar a versão do Node
      - uses: actions/setup-node@v3
        with:
          node-version: '18' # Certifique-se de que esta é a versão que você usa

      # ⬇️ PASSO 2: Instalar dependências
      - name: Install dependencies
        run: npm install

      # ⬇️ PASSO 3: Rodar o BUILD de produção explicitamente
      # Isso garante que a correção do apiUrl seja injetada.
      - name: Run Angular Build
        run: npm run build -- --configuration=production --base-href /

      # ⬇️ PASSO 4: Fazer o Deploy para o Azure SWA
      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WONDERFUL_RIVER_0D4566F1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload" 
    
          # NOVO: Diz ao SWA para PULAR o build do Oryx (que estava falhando)
          skip_app_build: true 
    
           # AJUSTE DE CAMINHO: Deve apontar para a pasta que contém o 'index.html'
           # Esta pasta foi gerada pelo 'ng build' manual no passo anterior.
          app_location: "dist/bolao-online-app-v5" 
          api_location: ""
          output_location: "" # Vazio, pois o app_location já aponta para a saída.
          
