name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Angular Build
        run: npm run build -- --configuration=production --base-href /
      
      # 💥 CORREÇÃO FORÇADA: COPIA O ARQUIVO DE ROTEAMENTO PARA A PASTA FINAL DE DEPLOY 💥
      # Isso garante que o SWA o encontre na raiz do deploy.
      - name: Copy SWA Config to Output
        run: cp staticwebapp.config.json dist/bolao-online-app-v5/browser/
        
      # ⬇️ Upload Build Artifact (usando a pasta que agora tem o config)
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4 
        with:
          name: angular-app-build
          path: dist/bolao-online-app-v5/browser 

      - name: Download Build Artifact
        uses: actions/download-artifact@v4 
        with:
          name: angular-app-build
          path: ./app_output_temp 

      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WONDERFUL_RIVER_0D4566F1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          skip_app_build: true
          app_location: "./app_output_temp" 
          api_location: ""
          output_location: ""
