name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # ⬇️ PASSO 1: Configurar a versão do Node
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      # ⬇️ PASSO 2: Instalar dependências
      - name: Install dependencies
        run: npm install

      # ⬇️ PASSO 3: Rodar o BUILD de produção (Cria a pasta: dist/bolao-online-app-v5/browser)
      - name: Run Angular Build
        run: npm run build -- --configuration=production --base-href /
        
      # 💥 NOVO PASSO (3.1): Empacota a pasta de build correta como um artefato
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: angular-app-build
          # Usamos o caminho aninhado que definimos no build.
          path: dist/bolao-online-app-v5/browser 

      # 💥 NOVO PASSO (3.2): Baixa o artefato em uma nova pasta temporária
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: angular-app-build
          # Cria uma pasta temporária simples para o deploy
          path: ./app_output_temp 

      # ⬇️ PASSO 4: Fazer o Deploy para o Azure SWA
      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WONDERFUL_RIVER_0D4566F1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          
          # Ignora o build, pois já fizemos isso.
          skip_app_build: true

          # APONTA DIRETAMENTE PARA A PASTA TEMPORÁRIA QUE CONTÉM O INDEX.HTML
          app_location: "./app_output_temp" 
          
          # Como a pasta app_output_temp SÓ tem o conteúdo do build, 
          # o output_location fica vazio.
          api_location: ""
          output_location: ""
