name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # ⬇️ NOVO PASSO 1: Instalar dependências
      - name: Install dependencies
        run: npm install

      # ⬇️ NOVO PASSO 2: Rodar o BUILD de produção e gerar a pasta 'dist/bolao-online-app-v5'
      # Isso garante que a correção do apiUrl seja injetada e o base-href esteja correto.
      - name: Run Angular Build
        run: npm run build -- --configuration=production --base-href /
        # Você pode usar 'ng build --configuration=production --base-href /' se o ng-cli estiver disponível globalmente no runner

      # ⬇️ O SWA AGORA VAI APENAS PEGAR OS ARQUIVOS JÁ COMPILADOS
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
        # ... (outras configurações)
        # NOVO: Mapeia o app_location para a pasta que contém o index.html
         app_location: "dist/bolao-online-app-v5" 
         api_location: ""
         # NOVO: Se app_location aponta para o index.html, output_location deve ser vazio.
         output_location: ""
          # Note: Reverti para 'dist/bolao-online-app-v5' pois é o caminho EXATO que você precisa
          # e incluí os passos manuais para garantir que o build aconteça ANTES do deploy.
